icons_format = "{icon}"

[theme]
theme = "modern"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome6"
#[icons.overrides]
#bat = ["|E|", "|_|", "|=|", "|F|"]
#bat_charging = "|^| "

[[block]]
block = "battery"
format = " $icon $percentage "
missing_format = ""
#charging_format = " $icon "
interval = 1

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2,prefix:Gi) "
[[block.click]]
button = "left"
cmd = "thunar ~"

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:3,prefix:Gi) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
max_vol = 100
step_width = 5
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "music"
format = "{ $icon $combo.str(max_w:30) $prev $next |}"
[[block.click]]
button = "left"
action = "play_pause"
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"

[[block]]
block = "net"
format = " $icon {$essid | LAN}"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
